### ISSUE TITLE
mde_installer.sh not working. It always finds itself as conflicting application.

### ISSUE THREAD

**Issue by SvenMarquardt5772** [microsoft/mdatp-xplat#68]
```
sudo ./mde_installer.sh --install --channel prod --onboard onboarding.py --tag GROUP <generic_name> --min_req --yes
--- mde_installer.sh v0.5.9 ---
./mde_installer.sh: Zeile 369: [: -lt: Einstelliger (unärer) Operator erwartet.
[v] minimal requirements met
[>] detected: ubuntu 20.04 focal (debian)
[>] scaled: 20.04
[v] set package manager: apt
/usr/bin/wget
[final] connected=OK
[v] connected
./mde_installer.sh: Zeile 401: Warnung: Kommansosubstitution: NULL byte in der Eingabe ignoriert.
[S] MDE not installed.
[x] found conflicting applications: [/opt/microsoft/mdatp/sbin/wdavdaemon], aborting
[*] exiting (5)
```
The script finds its binaries and thinks that these are conflicting binaries. 

Furthermore, because `set -euo pipefail` is not set, the script ignores some errors.

**Comment by SvenMarquardt5772** [comment]
The error with blocking its installation is the same as #51

**Comment by SvenMarquardt5772** [comment]
Resolved this with `sudo ./mde_installer.sh --remove` and afterwards `dpkg --remove mdeatp`.

**Comment by agarwalneetu** [comment]
Hi @SvenMarquardt5772, I was working on #51, and saw you mentioned #51 issue here. So, can I go assume "mdatp blocking his own installation issue" is resolved and can go ahead and close this issue ?

**Comment by SvenMarquardt5772** [comment]
Yes, I resolved it as described above.

**Comment by agarwalneetu** [comment]
can you please close it then issue #51, I can't close it.
________________________________

**Comment by agarwalneetu** [comment]
________________________________
From: Neetu Agarwal
Sent: Thursday, February 9, 2023 5:37 PM
To: Deepti Bhardwaj ***@***.***>; Amit Arora ***@***.***>; Mati Goldberg ***@***.***>; Luba Zlochin ***@***.***>
Subject: Onboarding failing after offboarding

Hi all,

I need your help in understanding the scenario below.

Problem Statement:

If try to onboard mdatp right after offboarding; onboarding is failing. This is happening because after offboarding, mdatp_offboard.json file is present at /etc/opt/microsoft/mdatp location which is blocking the onboarding process.

Though, This same thing is not happening during offboarding, the offboarding script automatically first delete the mdatp_onboard.json file and replaces it with mdatp_offboard.json file.


I need to understand two things:

      1. How offboarding is replacing mdatp_onboard.json file with mdatp_offboard.json file?

            I didn't find such code in the offboarding script. Also in edr.cpp,<https://microsoft.visualstudio.com/DefaultCollection/Windows%20Defender/_git/WD.Client.Mac?path=/src/daemon/lib/edr/src/edr.cpp&version=GBmaster&_a=contents> I found that during offboarding we are only setting orgID to null and not deleting any file.

      2. What could be the possible reason that mdatp_offboard.json file is blocking onboarding and not getting deleted?


Testing:

I tested this issue on multiple vms using both manual and automatic method; it's giving the same error.


Mitigation:

Issue is getting resolved after we manually delete mdatp_offboard.json file and then  onboard the device.

Thanks,
Neetu
